# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='csedept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dhansarihostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='gymkhana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subhansrihostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='umiamhostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('clear', models.IntegerField(default=0)),
            ],
        ),
    ]
