# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
